### PR TITLE
4.0.3 h62b0a5

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/soci-feedstock/pull/6

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
Ready for review and merge @conda-forge/soci

**Comment by marimeireles** [comment]
Hi @izahn, thank you for the PR.
It looks good!
Just because I'm curious and the history is shared between you and the bot. Did you added all of these mamba commands by yourself or is it an automated command by conda-forge now? 
Thanks :)

**Comment by izahn** [comment]
Happy to help! The bot did all the work, I just reviewed upstream, saw that the failing patches had been adopted there, and removed them from the recipe. The bot did everything else!

**Pull request merged**
